# Artificial Neural Network

### Importing the libraries

In [34]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [35]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [36]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values #the first 4 features are irrelevant and dont effect the result and exclude the last data point
y = dataset.iloc[:, -1].values #the depemndant variable is wether someone will stay or leave the bank 

In [37]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [38]:
print(y) #

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [39]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) #have to encode categorical datat into something that a machine can understand categories like male or female should be mapped into things such as like 1 or 0 
###this is for the gender section 
#for other things that are categorical have to use one hut encoding for thins such as countries

In [40]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [41]:
#this encodes the countries using one hut encoding and there is no relation in ordering of the countries 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [42]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [45]:
ann = tf.keras.models.Sequential() #tensor flow and keras libraries are now merged 

### Adding the input layer and the first hidden layer

In [46]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 
#this helps prevent overfitting and it is a fully connected layer 
#units is the number of neurons you want in the hidden layer 
#there is no rule of thumb for the number of units selected ajnd these are an example of parameter tuning asnd these are extrernjal to the machine learning process and these are then trained 
#the type of activation function helps to create the hidden layer 

### Adding the second hidden layer

In [47]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #this is simple to add the second layer, the only reason to change is to tune or change the number of neurons that are present in this layer  

#

### Adding the output layer

In [48]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #notice the output layer has only 1 output and the activation is sigmpoid. 
#or rather the dimensions of the output, since we are only outpiutting one value then you only need one neuron.
#since it is binary 
# if it was non binary class then there would be 3 output to onehut encode 


## Part 3 - Training the ANN

### Compiling the ANN

In [49]:
#adam optimiser uses stochastic gradinet descent, 
#the loss function for binary is always this for non binary it is categorical_crossentropy
#the activation should be softmax 
#several metrics can be selected at the same time 
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [50]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
#batch size gives the number of predictions that are compared and this is a hyperparamter that can be tuned 
#epochs, neural networks have to be trained over a set of epochs to learn properly. 


Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5694 - accuracy: 0.7490
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4873 - accuracy: 0.7975
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4561 - accuracy: 0.7983
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4399 - accuracy: 0.7979
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4329 - accuracy: 0.8014
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4295 - accuracy: 0.8035
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4278 - accuracy: 0.8048
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4260 - accuracy: 0.8064
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4246 - accuracy: 0.8069
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4229 - accura

The accuracy converged to 80% quite early 
this is stochastic cos when it is rerun then it produces an accuracy of 86%

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [51]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#not the fit transform as the fit transform gives the mean and the standard deviation 
#this is a probability so then we set a condition--then this makes it into a boolean statement 


[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [54]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 194  211]]


0.86