# Data Preprocessing Template

## Importing the libraries

In [48]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

## Importing the dataset

In [49]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [50]:
print (X)
print (y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [51]:
from sklearn.impute import SimpleImputer 
#imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer=SimpleImputer(missing_values=np.nan, strategy='mean' )
imputer.fit(X[:, 1:3 ]) #in this range we are trying to exclude all strings as this can lead to error 
X[:, 1:3 ]=imputer.transform(X[:, 1:3 ]) #this uses tge same range and updates the vbalues 

In [21]:
print (X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [52]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder 
ct =  ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough') #transformers variable takes on three arguments and the reaminder argument takes 

#have to say want to do encoding, what type of encodign and the index and this is done as  a tuple 
#theindex is 0 because we are only appluing to the country column 

#passthrough is to keep the values that aren't onehut encoded 

X=np.array(ct.fit_transform(X)) # set it equal to the value and themn have toi set the value of thge x as a numpoay array to uyse it in the future machine learning
#Have to force it to be a numpy array as we would use this in the future

In [54]:
print (X)
print(y)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [55]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) #this function  is different to the previous one it transforms and fits the
#the function automatically 

Encoding categorical data


In [56]:
print (y)


[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [61]:
#Splitting a dataset
#traintestsplit creates 4 seperate sets a pair of matrix features and depentnt variables 
#for the test set 
#xtest, xtrain ytest, ytrain
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(X,y,test_size=0.2,random_state=1)

In [62]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [63]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [66]:
print(x_test)


[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [69]:
print(y_test)

[0 1]


Feature **scaling** **bold text**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)